title: your document title
description: your document description
theme: just-the-docs
url: https://github.com/inducedcandle172/inducedcandle172

aux_links:
  Repository: https://github.com/inducedcandle172/inducedcandle172
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
